# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/szabandith/Delivery/Tek3/CPP/B-CPP-500-PAR-5-2-rtype-danny.duong

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/szabandith/Delivery/Tek3/CPP/B-CPP-500-PAR-5-2-rtype-danny.duong

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/szabandith/Delivery/Tek3/CPP/B-CPP-500-PAR-5-2-rtype-danny.duong/CMakeFiles /home/szabandith/Delivery/Tek3/CPP/B-CPP-500-PAR-5-2-rtype-danny.duong//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/szabandith/Delivery/Tek3/CPP/B-CPP-500-PAR-5-2-rtype-danny.duong/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named rtype_server

# Build rule for target.
rtype_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rtype_server
.PHONY : rtype_server

# fast build rule for target.
rtype_server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_server.dir/build.make CMakeFiles/rtype_server.dir/build
.PHONY : rtype_server/fast

#=============================================================================
# Target rules for targets named rtype_client

# Build rule for target.
rtype_client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rtype_client
.PHONY : rtype_client

# fast build rule for target.
rtype_client/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_client.dir/build.make CMakeFiles/rtype_client.dir/build
.PHONY : rtype_client/fast

Game/src/Client.o: Game/src/Client.cpp.o
.PHONY : Game/src/Client.o

# target to build an object file
Game/src/Client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_client.dir/build.make CMakeFiles/rtype_client.dir/Game/src/Client.cpp.o
.PHONY : Game/src/Client.cpp.o

Game/src/Client.i: Game/src/Client.cpp.i
.PHONY : Game/src/Client.i

# target to preprocess a source file
Game/src/Client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_client.dir/build.make CMakeFiles/rtype_client.dir/Game/src/Client.cpp.i
.PHONY : Game/src/Client.cpp.i

Game/src/Client.s: Game/src/Client.cpp.s
.PHONY : Game/src/Client.s

# target to generate assembly for a file
Game/src/Client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_client.dir/build.make CMakeFiles/rtype_client.dir/Game/src/Client.cpp.s
.PHONY : Game/src/Client.cpp.s

Game/src/Game.o: Game/src/Game.cpp.o
.PHONY : Game/src/Game.o

# target to build an object file
Game/src/Game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_client.dir/build.make CMakeFiles/rtype_client.dir/Game/src/Game.cpp.o
.PHONY : Game/src/Game.cpp.o

Game/src/Game.i: Game/src/Game.cpp.i
.PHONY : Game/src/Game.i

# target to preprocess a source file
Game/src/Game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_client.dir/build.make CMakeFiles/rtype_client.dir/Game/src/Game.cpp.i
.PHONY : Game/src/Game.cpp.i

Game/src/Game.s: Game/src/Game.cpp.s
.PHONY : Game/src/Game.s

# target to generate assembly for a file
Game/src/Game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_client.dir/build.make CMakeFiles/rtype_client.dir/Game/src/Game.cpp.s
.PHONY : Game/src/Game.cpp.s

Game/src/Gameplay/Component.o: Game/src/Gameplay/Component.cpp.o
.PHONY : Game/src/Gameplay/Component.o

# target to build an object file
Game/src/Gameplay/Component.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_client.dir/build.make CMakeFiles/rtype_client.dir/Game/src/Gameplay/Component.cpp.o
.PHONY : Game/src/Gameplay/Component.cpp.o

Game/src/Gameplay/Component.i: Game/src/Gameplay/Component.cpp.i
.PHONY : Game/src/Gameplay/Component.i

# target to preprocess a source file
Game/src/Gameplay/Component.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_client.dir/build.make CMakeFiles/rtype_client.dir/Game/src/Gameplay/Component.cpp.i
.PHONY : Game/src/Gameplay/Component.cpp.i

Game/src/Gameplay/Component.s: Game/src/Gameplay/Component.cpp.s
.PHONY : Game/src/Gameplay/Component.s

# target to generate assembly for a file
Game/src/Gameplay/Component.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_client.dir/build.make CMakeFiles/rtype_client.dir/Game/src/Gameplay/Component.cpp.s
.PHONY : Game/src/Gameplay/Component.cpp.s

Game/src/Gameplay/Configuration.o: Game/src/Gameplay/Configuration.cpp.o
.PHONY : Game/src/Gameplay/Configuration.o

# target to build an object file
Game/src/Gameplay/Configuration.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_client.dir/build.make CMakeFiles/rtype_client.dir/Game/src/Gameplay/Configuration.cpp.o
.PHONY : Game/src/Gameplay/Configuration.cpp.o

Game/src/Gameplay/Configuration.i: Game/src/Gameplay/Configuration.cpp.i
.PHONY : Game/src/Gameplay/Configuration.i

# target to preprocess a source file
Game/src/Gameplay/Configuration.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_client.dir/build.make CMakeFiles/rtype_client.dir/Game/src/Gameplay/Configuration.cpp.i
.PHONY : Game/src/Gameplay/Configuration.cpp.i

Game/src/Gameplay/Configuration.s: Game/src/Gameplay/Configuration.cpp.s
.PHONY : Game/src/Gameplay/Configuration.s

# target to generate assembly for a file
Game/src/Gameplay/Configuration.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_client.dir/build.make CMakeFiles/rtype_client.dir/Game/src/Gameplay/Configuration.cpp.s
.PHONY : Game/src/Gameplay/Configuration.cpp.s

Game/src/Gameplay/Entity.o: Game/src/Gameplay/Entity.cpp.o
.PHONY : Game/src/Gameplay/Entity.o

# target to build an object file
Game/src/Gameplay/Entity.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_client.dir/build.make CMakeFiles/rtype_client.dir/Game/src/Gameplay/Entity.cpp.o
.PHONY : Game/src/Gameplay/Entity.cpp.o

Game/src/Gameplay/Entity.i: Game/src/Gameplay/Entity.cpp.i
.PHONY : Game/src/Gameplay/Entity.i

# target to preprocess a source file
Game/src/Gameplay/Entity.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_client.dir/build.make CMakeFiles/rtype_client.dir/Game/src/Gameplay/Entity.cpp.i
.PHONY : Game/src/Gameplay/Entity.cpp.i

Game/src/Gameplay/Entity.s: Game/src/Gameplay/Entity.cpp.s
.PHONY : Game/src/Gameplay/Entity.s

# target to generate assembly for a file
Game/src/Gameplay/Entity.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_client.dir/build.make CMakeFiles/rtype_client.dir/Game/src/Gameplay/Entity.cpp.s
.PHONY : Game/src/Gameplay/Entity.cpp.s

Game/src/Gameplay/GameOver.o: Game/src/Gameplay/GameOver.cpp.o
.PHONY : Game/src/Gameplay/GameOver.o

# target to build an object file
Game/src/Gameplay/GameOver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_client.dir/build.make CMakeFiles/rtype_client.dir/Game/src/Gameplay/GameOver.cpp.o
.PHONY : Game/src/Gameplay/GameOver.cpp.o

Game/src/Gameplay/GameOver.i: Game/src/Gameplay/GameOver.cpp.i
.PHONY : Game/src/Gameplay/GameOver.i

# target to preprocess a source file
Game/src/Gameplay/GameOver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_client.dir/build.make CMakeFiles/rtype_client.dir/Game/src/Gameplay/GameOver.cpp.i
.PHONY : Game/src/Gameplay/GameOver.cpp.i

Game/src/Gameplay/GameOver.s: Game/src/Gameplay/GameOver.cpp.s
.PHONY : Game/src/Gameplay/GameOver.s

# target to generate assembly for a file
Game/src/Gameplay/GameOver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_client.dir/build.make CMakeFiles/rtype_client.dir/Game/src/Gameplay/GameOver.cpp.s
.PHONY : Game/src/Gameplay/GameOver.cpp.s

Game/src/Gameplay/MovementSystem.o: Game/src/Gameplay/MovementSystem.cpp.o
.PHONY : Game/src/Gameplay/MovementSystem.o

# target to build an object file
Game/src/Gameplay/MovementSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_client.dir/build.make CMakeFiles/rtype_client.dir/Game/src/Gameplay/MovementSystem.cpp.o
.PHONY : Game/src/Gameplay/MovementSystem.cpp.o

Game/src/Gameplay/MovementSystem.i: Game/src/Gameplay/MovementSystem.cpp.i
.PHONY : Game/src/Gameplay/MovementSystem.i

# target to preprocess a source file
Game/src/Gameplay/MovementSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_client.dir/build.make CMakeFiles/rtype_client.dir/Game/src/Gameplay/MovementSystem.cpp.i
.PHONY : Game/src/Gameplay/MovementSystem.cpp.i

Game/src/Gameplay/MovementSystem.s: Game/src/Gameplay/MovementSystem.cpp.s
.PHONY : Game/src/Gameplay/MovementSystem.s

# target to generate assembly for a file
Game/src/Gameplay/MovementSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_client.dir/build.make CMakeFiles/rtype_client.dir/Game/src/Gameplay/MovementSystem.cpp.s
.PHONY : Game/src/Gameplay/MovementSystem.cpp.s

Game/src/Gameplay/Player.o: Game/src/Gameplay/Player.cpp.o
.PHONY : Game/src/Gameplay/Player.o

# target to build an object file
Game/src/Gameplay/Player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_client.dir/build.make CMakeFiles/rtype_client.dir/Game/src/Gameplay/Player.cpp.o
.PHONY : Game/src/Gameplay/Player.cpp.o

Game/src/Gameplay/Player.i: Game/src/Gameplay/Player.cpp.i
.PHONY : Game/src/Gameplay/Player.i

# target to preprocess a source file
Game/src/Gameplay/Player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_client.dir/build.make CMakeFiles/rtype_client.dir/Game/src/Gameplay/Player.cpp.i
.PHONY : Game/src/Gameplay/Player.cpp.i

Game/src/Gameplay/Player.s: Game/src/Gameplay/Player.cpp.s
.PHONY : Game/src/Gameplay/Player.s

# target to generate assembly for a file
Game/src/Gameplay/Player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_client.dir/build.make CMakeFiles/rtype_client.dir/Game/src/Gameplay/Player.cpp.s
.PHONY : Game/src/Gameplay/Player.cpp.s

Game/src/Gameplay/System.o: Game/src/Gameplay/System.cpp.o
.PHONY : Game/src/Gameplay/System.o

# target to build an object file
Game/src/Gameplay/System.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_client.dir/build.make CMakeFiles/rtype_client.dir/Game/src/Gameplay/System.cpp.o
.PHONY : Game/src/Gameplay/System.cpp.o

Game/src/Gameplay/System.i: Game/src/Gameplay/System.cpp.i
.PHONY : Game/src/Gameplay/System.i

# target to preprocess a source file
Game/src/Gameplay/System.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_client.dir/build.make CMakeFiles/rtype_client.dir/Game/src/Gameplay/System.cpp.i
.PHONY : Game/src/Gameplay/System.cpp.i

Game/src/Gameplay/System.s: Game/src/Gameplay/System.cpp.s
.PHONY : Game/src/Gameplay/System.s

# target to generate assembly for a file
Game/src/Gameplay/System.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_client.dir/build.make CMakeFiles/rtype_client.dir/Game/src/Gameplay/System.cpp.s
.PHONY : Game/src/Gameplay/System.cpp.s

Game/src/Init/Button.o: Game/src/Init/Button.cpp.o
.PHONY : Game/src/Init/Button.o

# target to build an object file
Game/src/Init/Button.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_client.dir/build.make CMakeFiles/rtype_client.dir/Game/src/Init/Button.cpp.o
.PHONY : Game/src/Init/Button.cpp.o

Game/src/Init/Button.i: Game/src/Init/Button.cpp.i
.PHONY : Game/src/Init/Button.i

# target to preprocess a source file
Game/src/Init/Button.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_client.dir/build.make CMakeFiles/rtype_client.dir/Game/src/Init/Button.cpp.i
.PHONY : Game/src/Init/Button.cpp.i

Game/src/Init/Button.s: Game/src/Init/Button.cpp.s
.PHONY : Game/src/Init/Button.s

# target to generate assembly for a file
Game/src/Init/Button.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_client.dir/build.make CMakeFiles/rtype_client.dir/Game/src/Init/Button.cpp.s
.PHONY : Game/src/Init/Button.cpp.s

Game/src/Init/InitTexture.o: Game/src/Init/InitTexture.cpp.o
.PHONY : Game/src/Init/InitTexture.o

# target to build an object file
Game/src/Init/InitTexture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_client.dir/build.make CMakeFiles/rtype_client.dir/Game/src/Init/InitTexture.cpp.o
.PHONY : Game/src/Init/InitTexture.cpp.o

Game/src/Init/InitTexture.i: Game/src/Init/InitTexture.cpp.i
.PHONY : Game/src/Init/InitTexture.i

# target to preprocess a source file
Game/src/Init/InitTexture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_client.dir/build.make CMakeFiles/rtype_client.dir/Game/src/Init/InitTexture.cpp.i
.PHONY : Game/src/Init/InitTexture.cpp.i

Game/src/Init/InitTexture.s: Game/src/Init/InitTexture.cpp.s
.PHONY : Game/src/Init/InitTexture.s

# target to generate assembly for a file
Game/src/Init/InitTexture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_client.dir/build.make CMakeFiles/rtype_client.dir/Game/src/Init/InitTexture.cpp.s
.PHONY : Game/src/Init/InitTexture.cpp.s

Game/src/Init/JsonRead.o: Game/src/Init/JsonRead.cpp.o
.PHONY : Game/src/Init/JsonRead.o

# target to build an object file
Game/src/Init/JsonRead.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_client.dir/build.make CMakeFiles/rtype_client.dir/Game/src/Init/JsonRead.cpp.o
.PHONY : Game/src/Init/JsonRead.cpp.o

Game/src/Init/JsonRead.i: Game/src/Init/JsonRead.cpp.i
.PHONY : Game/src/Init/JsonRead.i

# target to preprocess a source file
Game/src/Init/JsonRead.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_client.dir/build.make CMakeFiles/rtype_client.dir/Game/src/Init/JsonRead.cpp.i
.PHONY : Game/src/Init/JsonRead.cpp.i

Game/src/Init/JsonRead.s: Game/src/Init/JsonRead.cpp.s
.PHONY : Game/src/Init/JsonRead.s

# target to generate assembly for a file
Game/src/Init/JsonRead.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_client.dir/build.make CMakeFiles/rtype_client.dir/Game/src/Init/JsonRead.cpp.s
.PHONY : Game/src/Init/JsonRead.cpp.s

Game/src/Init/Music.o: Game/src/Init/Music.cpp.o
.PHONY : Game/src/Init/Music.o

# target to build an object file
Game/src/Init/Music.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_client.dir/build.make CMakeFiles/rtype_client.dir/Game/src/Init/Music.cpp.o
.PHONY : Game/src/Init/Music.cpp.o

Game/src/Init/Music.i: Game/src/Init/Music.cpp.i
.PHONY : Game/src/Init/Music.i

# target to preprocess a source file
Game/src/Init/Music.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_client.dir/build.make CMakeFiles/rtype_client.dir/Game/src/Init/Music.cpp.i
.PHONY : Game/src/Init/Music.cpp.i

Game/src/Init/Music.s: Game/src/Init/Music.cpp.s
.PHONY : Game/src/Init/Music.s

# target to generate assembly for a file
Game/src/Init/Music.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_client.dir/build.make CMakeFiles/rtype_client.dir/Game/src/Init/Music.cpp.s
.PHONY : Game/src/Init/Music.cpp.s

Game/src/Init/Parralax.o: Game/src/Init/Parralax.cpp.o
.PHONY : Game/src/Init/Parralax.o

# target to build an object file
Game/src/Init/Parralax.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_client.dir/build.make CMakeFiles/rtype_client.dir/Game/src/Init/Parralax.cpp.o
.PHONY : Game/src/Init/Parralax.cpp.o

Game/src/Init/Parralax.i: Game/src/Init/Parralax.cpp.i
.PHONY : Game/src/Init/Parralax.i

# target to preprocess a source file
Game/src/Init/Parralax.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_client.dir/build.make CMakeFiles/rtype_client.dir/Game/src/Init/Parralax.cpp.i
.PHONY : Game/src/Init/Parralax.cpp.i

Game/src/Init/Parralax.s: Game/src/Init/Parralax.cpp.s
.PHONY : Game/src/Init/Parralax.s

# target to generate assembly for a file
Game/src/Init/Parralax.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_client.dir/build.make CMakeFiles/rtype_client.dir/Game/src/Init/Parralax.cpp.s
.PHONY : Game/src/Init/Parralax.cpp.s

Game/src/Init/Sound.o: Game/src/Init/Sound.cpp.o
.PHONY : Game/src/Init/Sound.o

# target to build an object file
Game/src/Init/Sound.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_client.dir/build.make CMakeFiles/rtype_client.dir/Game/src/Init/Sound.cpp.o
.PHONY : Game/src/Init/Sound.cpp.o

Game/src/Init/Sound.i: Game/src/Init/Sound.cpp.i
.PHONY : Game/src/Init/Sound.i

# target to preprocess a source file
Game/src/Init/Sound.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_client.dir/build.make CMakeFiles/rtype_client.dir/Game/src/Init/Sound.cpp.i
.PHONY : Game/src/Init/Sound.cpp.i

Game/src/Init/Sound.s: Game/src/Init/Sound.cpp.s
.PHONY : Game/src/Init/Sound.s

# target to generate assembly for a file
Game/src/Init/Sound.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_client.dir/build.make CMakeFiles/rtype_client.dir/Game/src/Init/Sound.cpp.s
.PHONY : Game/src/Init/Sound.cpp.s

Game/src/Init/TextField.o: Game/src/Init/TextField.cpp.o
.PHONY : Game/src/Init/TextField.o

# target to build an object file
Game/src/Init/TextField.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_client.dir/build.make CMakeFiles/rtype_client.dir/Game/src/Init/TextField.cpp.o
.PHONY : Game/src/Init/TextField.cpp.o

Game/src/Init/TextField.i: Game/src/Init/TextField.cpp.i
.PHONY : Game/src/Init/TextField.i

# target to preprocess a source file
Game/src/Init/TextField.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_client.dir/build.make CMakeFiles/rtype_client.dir/Game/src/Init/TextField.cpp.i
.PHONY : Game/src/Init/TextField.cpp.i

Game/src/Init/TextField.s: Game/src/Init/TextField.cpp.s
.PHONY : Game/src/Init/TextField.s

# target to generate assembly for a file
Game/src/Init/TextField.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_client.dir/build.make CMakeFiles/rtype_client.dir/Game/src/Init/TextField.cpp.s
.PHONY : Game/src/Init/TextField.cpp.s

Game/src/Init/Window.o: Game/src/Init/Window.cpp.o
.PHONY : Game/src/Init/Window.o

# target to build an object file
Game/src/Init/Window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_client.dir/build.make CMakeFiles/rtype_client.dir/Game/src/Init/Window.cpp.o
.PHONY : Game/src/Init/Window.cpp.o

Game/src/Init/Window.i: Game/src/Init/Window.cpp.i
.PHONY : Game/src/Init/Window.i

# target to preprocess a source file
Game/src/Init/Window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_client.dir/build.make CMakeFiles/rtype_client.dir/Game/src/Init/Window.cpp.i
.PHONY : Game/src/Init/Window.cpp.i

Game/src/Init/Window.s: Game/src/Init/Window.cpp.s
.PHONY : Game/src/Init/Window.s

# target to generate assembly for a file
Game/src/Init/Window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_client.dir/build.make CMakeFiles/rtype_client.dir/Game/src/Init/Window.cpp.s
.PHONY : Game/src/Init/Window.cpp.s

Game/src/Menu.o: Game/src/Menu.cpp.o
.PHONY : Game/src/Menu.o

# target to build an object file
Game/src/Menu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_client.dir/build.make CMakeFiles/rtype_client.dir/Game/src/Menu.cpp.o
.PHONY : Game/src/Menu.cpp.o

Game/src/Menu.i: Game/src/Menu.cpp.i
.PHONY : Game/src/Menu.i

# target to preprocess a source file
Game/src/Menu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_client.dir/build.make CMakeFiles/rtype_client.dir/Game/src/Menu.cpp.i
.PHONY : Game/src/Menu.cpp.i

Game/src/Menu.s: Game/src/Menu.cpp.s
.PHONY : Game/src/Menu.s

# target to generate assembly for a file
Game/src/Menu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_client.dir/build.make CMakeFiles/rtype_client.dir/Game/src/Menu.cpp.s
.PHONY : Game/src/Menu.cpp.s

Game/src/main.o: Game/src/main.cpp.o
.PHONY : Game/src/main.o

# target to build an object file
Game/src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_client.dir/build.make CMakeFiles/rtype_client.dir/Game/src/main.cpp.o
.PHONY : Game/src/main.cpp.o

Game/src/main.i: Game/src/main.cpp.i
.PHONY : Game/src/main.i

# target to preprocess a source file
Game/src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_client.dir/build.make CMakeFiles/rtype_client.dir/Game/src/main.cpp.i
.PHONY : Game/src/main.cpp.i

Game/src/main.s: Game/src/main.cpp.s
.PHONY : Game/src/main.s

# target to generate assembly for a file
Game/src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_client.dir/build.make CMakeFiles/rtype_client.dir/Game/src/main.cpp.s
.PHONY : Game/src/main.cpp.s

Server/Server.o: Server/Server.cpp.o
.PHONY : Server/Server.o

# target to build an object file
Server/Server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_server.dir/build.make CMakeFiles/rtype_server.dir/Server/Server.cpp.o
.PHONY : Server/Server.cpp.o

Server/Server.i: Server/Server.cpp.i
.PHONY : Server/Server.i

# target to preprocess a source file
Server/Server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_server.dir/build.make CMakeFiles/rtype_server.dir/Server/Server.cpp.i
.PHONY : Server/Server.cpp.i

Server/Server.s: Server/Server.cpp.s
.PHONY : Server/Server.s

# target to generate assembly for a file
Server/Server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_server.dir/build.make CMakeFiles/rtype_server.dir/Server/Server.cpp.s
.PHONY : Server/Server.cpp.s

Server/main.o: Server/main.cpp.o
.PHONY : Server/main.o

# target to build an object file
Server/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_server.dir/build.make CMakeFiles/rtype_server.dir/Server/main.cpp.o
.PHONY : Server/main.cpp.o

Server/main.i: Server/main.cpp.i
.PHONY : Server/main.i

# target to preprocess a source file
Server/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_server.dir/build.make CMakeFiles/rtype_server.dir/Server/main.cpp.i
.PHONY : Server/main.cpp.i

Server/main.s: Server/main.cpp.s
.PHONY : Server/main.s

# target to generate assembly for a file
Server/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_server.dir/build.make CMakeFiles/rtype_server.dir/Server/main.cpp.s
.PHONY : Server/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... rtype_client"
	@echo "... rtype_server"
	@echo "... Game/src/Client.o"
	@echo "... Game/src/Client.i"
	@echo "... Game/src/Client.s"
	@echo "... Game/src/Game.o"
	@echo "... Game/src/Game.i"
	@echo "... Game/src/Game.s"
	@echo "... Game/src/Gameplay/Component.o"
	@echo "... Game/src/Gameplay/Component.i"
	@echo "... Game/src/Gameplay/Component.s"
	@echo "... Game/src/Gameplay/Configuration.o"
	@echo "... Game/src/Gameplay/Configuration.i"
	@echo "... Game/src/Gameplay/Configuration.s"
	@echo "... Game/src/Gameplay/Entity.o"
	@echo "... Game/src/Gameplay/Entity.i"
	@echo "... Game/src/Gameplay/Entity.s"
	@echo "... Game/src/Gameplay/GameOver.o"
	@echo "... Game/src/Gameplay/GameOver.i"
	@echo "... Game/src/Gameplay/GameOver.s"
	@echo "... Game/src/Gameplay/MovementSystem.o"
	@echo "... Game/src/Gameplay/MovementSystem.i"
	@echo "... Game/src/Gameplay/MovementSystem.s"
	@echo "... Game/src/Gameplay/Player.o"
	@echo "... Game/src/Gameplay/Player.i"
	@echo "... Game/src/Gameplay/Player.s"
	@echo "... Game/src/Gameplay/System.o"
	@echo "... Game/src/Gameplay/System.i"
	@echo "... Game/src/Gameplay/System.s"
	@echo "... Game/src/Init/Button.o"
	@echo "... Game/src/Init/Button.i"
	@echo "... Game/src/Init/Button.s"
	@echo "... Game/src/Init/InitTexture.o"
	@echo "... Game/src/Init/InitTexture.i"
	@echo "... Game/src/Init/InitTexture.s"
	@echo "... Game/src/Init/JsonRead.o"
	@echo "... Game/src/Init/JsonRead.i"
	@echo "... Game/src/Init/JsonRead.s"
	@echo "... Game/src/Init/Music.o"
	@echo "... Game/src/Init/Music.i"
	@echo "... Game/src/Init/Music.s"
	@echo "... Game/src/Init/Parralax.o"
	@echo "... Game/src/Init/Parralax.i"
	@echo "... Game/src/Init/Parralax.s"
	@echo "... Game/src/Init/Sound.o"
	@echo "... Game/src/Init/Sound.i"
	@echo "... Game/src/Init/Sound.s"
	@echo "... Game/src/Init/TextField.o"
	@echo "... Game/src/Init/TextField.i"
	@echo "... Game/src/Init/TextField.s"
	@echo "... Game/src/Init/Window.o"
	@echo "... Game/src/Init/Window.i"
	@echo "... Game/src/Init/Window.s"
	@echo "... Game/src/Menu.o"
	@echo "... Game/src/Menu.i"
	@echo "... Game/src/Menu.s"
	@echo "... Game/src/main.o"
	@echo "... Game/src/main.i"
	@echo "... Game/src/main.s"
	@echo "... Server/Server.o"
	@echo "... Server/Server.i"
	@echo "... Server/Server.s"
	@echo "... Server/main.o"
	@echo "... Server/main.i"
	@echo "... Server/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

