FROM ubuntu:22.04 as builder

SHELL ["/bin/bash", "-c"]

RUN apt-get update

RUN apt-get -y install build-essential g++ libasio-dev cmake

WORKDIR /Server

COPY . .

RUN cmake .

RUN make

FROM ubuntu:22.04

COPY --from=builder /Server/rtype_server ./rtype_server

EXPOSE 12345

ENTRYPOINT [ "./rtype_server" ]